### PR TITLE
fix(testing): add support for jest.config.js

### LINKED ISSUE #100: tsdx test ignores snapshotSerializers in jest.config.js
### Current Behavior

If I run `tsdx test --env=jsdom --coverage` Jest will not use the snapshot serializers defined in the `jest.config.js` and fail all my snapshots.

### Expected behavior

When I run `tsdx test --env=jsdom --coverage` it should use the snapshot serializers defined in the `jest.config.js`.

### Suggested solution(s)

Pick up the config in the `jest.config.js` or be able to define a snapshot serializers via the cli.

### Additional context

When I run `jest` all my snapshots pass.
I am using `jest-emotion` for the snapshot serializers.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX             |   0.5.9    |
| TypeScript       |   3.4.5    |
| Browser          |   Firefox  |
| npm/Yarn         |   npm      |
| Operating System | OSX 10.14.4|

### PR DESCRIPTION
**Pull request by Aidurber**
Currently, `jest.config.js` is ignored. My fix is to try and check if there is a `jest.config.js`, if so then we just merge it into the jestConfig. 

This fixes #100 . 

Issue #150 is in a similar vein to this but that needs some more work.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -460,15 +460,26 @@ prog
...
+        relativePath => path.resolve(__dirname, '..', relativePath),
+        paths.appRoot
+      ),
+      ...appPackageJson.jest,
+    };
+    try {
+      // Allow overriding with jest.config
+      const jestConfigContents = require(path.resolve(
+        paths.appRoot,
+        'jest.config.js'
```
Comment (jaredpalmer) [inline src/index.ts]: We should add `jestConfig: resolveApp('./jest.config.js)` to `paths` and use it here.

Comment (Aidurber) [reply src/index.ts]: Yep, makes sense 👍

**Comment by agilgur5** [comment]
@allcontributors please add @Aidurber for code
